name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # This workflow will run on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version your project needs

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Instructs npm to install dependencies in the frontend directory

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend # Instructs npm to run the build command in the frontend directory

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          publish_branch: gh-pages # The branch to deploy your static files to
